export const projects = [
  { id: 1, name: 'Skyline Residences', category: 'residential', year: '2024', location: 'Addis Ababa', area: '4,200 m²', desc: 'A luxury residential complex blending Ethiopian heritage with ultra-modern living. Floor-to-ceiling glass facades capture panoramic city views while maintaining thermal efficiency.', details: 'This 12-story residential tower features cascading terraces with native landscaping, creating a vertical garden effect. The interior spaces prioritize natural light and cross-ventilation, reducing energy consumption by 40%.', status: 'Completed', client: 'Private Developer' },
  { id: 2, name: 'Nexus Tower', category: 'commercial', year: '2024', location: 'Dubai, UAE', area: '18,500 m²', desc: 'A flagship commercial tower with a dynamic double-skin facade that responds to solar conditions, housing 30 floors of premium office and retail space.', details: 'The parametric facade system uses algorithmic patterns inspired by Islamic geometry, combining cultural reference with cutting-edge environmental performance.', status: 'In Progress', client: 'Nexus Group' },
  { id: 3, name: 'Zen Living Apartments', category: 'interior', year: '2023', location: 'Tokyo, Japan', area: '850 m²', desc: 'Minimalist apartment interiors embracing Japanese Wabi-Sabi philosophy with warm natural materials and fluid spatial transitions.', details: 'Each unit features moveable partition walls, hidden storage systems, and a material palette of Japanese cypress, hand-finished concrete, and washi paper screens.', status: 'Completed', client: 'Zen Properties' },
  { id: 4, name: 'Green District', category: 'urban', year: '2025', location: 'Nairobi, Kenya', area: '120,000 m²', desc: 'A sustainable mixed-use urban district masterplan prioritizing pedestrian experience, green infrastructure, and community-driven design.', details: 'The plan creates a car-free zone with integrated urban farming, rainwater harvesting systems, solar corridors, and over 40% green space coverage.', status: 'Planning', client: 'City of Nairobi' },
  { id: 5, name: 'The Glass House', category: 'residential', year: '2023', location: 'Cape Town, SA', area: '1,800 m²', desc: 'A contemporary family residence cantilevered over a hillside, designed for seamless indoor-outdoor living with uninterrupted ocean views.', details: 'Structural glass walls dissolve boundaries between interior warmth and the dramatic coastal landscape. The home achieves net-zero energy through integrated photovoltaics.', status: 'Completed', client: 'Private Client' },
  { id: 6, name: 'Aurora Cultural Center', category: 'commercial', year: '2024', location: 'Stockholm, Sweden', area: '8,200 m²', desc: 'A cultural institution wrapped in a responsive light-emitting facade that transforms into a public art canvas after dark.', details: 'The building houses galleries, performance spaces, and a rooftop observatory. The facade uses 12,000 individually addressable LED nodes embedded in translucent panels.', status: 'In Progress', client: 'Stockholm Municipality' },
  { id: 7, name: 'Studio Loft Collective', category: 'interior', year: '2024', location: 'Berlin, Germany', area: '2,400 m²', desc: 'Converted industrial warehouse into co-working creative studios with raw materiality and precision-crafted insertions.', details: 'Preserved original steel trusses and brick walls serve as the backdrop for floating timber pods, glass meeting rooms, and a central double-height atrium.', status: 'Completed', client: 'Creative Hub Berlin' },
  { id: 8, name: 'Riverside Park Revival', category: 'urban', year: '2025', location: 'Addis Ababa', area: '85,000 m²', desc: 'Public waterfront regeneration transforming an underused riverbank into a vibrant ecological and recreational corridor.', details: 'The design integrates bioswales, native planting, amphitheaters, play areas, cycling paths, and floating pavilions along a 2km stretch of the Little Akaki River.', status: 'Planning', client: 'Addis Ababa City Admin' },
];

export const products = [
  { id: 1, name: 'Modern Villa Plans', category: 'plans', price: 299, originalPrice: 399, desc: 'Complete architectural plans for a 3-bedroom modern villa with construction details.', bg: 'plans' },
  { id: 2, name: 'Office Tower 3D Model', category: '3d', price: 199, originalPrice: null, desc: 'Detailed 3D model of a 20-story commercial tower. Includes Revit & SketchUp files.', bg: '3d' },
  { id: 3, name: 'Interior Design Template Pack', category: 'interior', price: 149, originalPrice: 199, desc: 'Set of 10 interior layout templates for residential projects. Ready to customize.', bg: 'interior' },
  { id: 4, name: 'Urban Concept Pack', category: 'concept', price: 349, originalPrice: null, desc: 'Masterplan concept pack including site analysis tools, zoning templates, and diagrams.', bg: 'concept' },
  { id: 5, name: 'Residential Bundle', category: 'plans', price: 499, originalPrice: 699, desc: 'Bundle of 5 residential floor plans covering apartments, duplexes, and villas.', bg: 'plans' },
  { id: 6, name: 'Minimalist Apartment Plans', category: 'plans', price: 179, originalPrice: null, desc: 'Clean, efficient apartment layouts optimized for urban living. 1-3 bedroom options.', bg: 'interior' },
];

export const team = [
  { id: 1, name: 'Nahom Tassew', role: 'Founder & Principal Architect', bio: 'Visionary architect blending Ethiopian heritage with futuristic design. 10+ years of international experience.', initials: 'NT', gradient: 'linear-gradient(135deg, #00d4ff, #0088aa)' },
  { id: 2, name: 'Sara Bekele', role: 'Senior Architect', bio: 'Specialist in sustainable design and biophilic architecture. Leads residential projects.', initials: 'SB', gradient: 'linear-gradient(135deg, #c9a84c, #907530)' },
  { id: 3, name: 'Daniel Asfaw', role: '3D Visualization Lead', bio: 'Creates photorealistic renders and immersive walkthroughs that bring designs to life.', initials: 'DA', gradient: 'linear-gradient(135deg, #00ff88, #00aa55)' },
  { id: 4, name: 'Meron Hailu', role: 'Interior Designer', bio: 'Crafts spaces that balance aesthetics with functionality. Expert in material curation.', initials: 'MH', gradient: 'linear-gradient(135deg, #ff6b9d, #c0392b)' },
  { id: 5, name: 'Yonas Tadesse', role: 'Project Manager', bio: 'Ensures projects are delivered on time and within budget with meticulous coordination.', initials: 'YT', gradient: 'linear-gradient(135deg, #9b59b6, #6c3483)' },
  { id: 6, name: 'Helen Girma', role: 'Urban Planner', bio: 'Designs livable cities through community-focused masterplanning and green infrastructure.', initials: 'HG', gradient: 'linear-gradient(135deg, #f39c12, #d68910)' },
];

export const jobs = [
  { id: 1, title: 'Junior Architect', type: 'Full-time', location: 'Addis Ababa', dept: 'Design', desc: 'Join our design team to work on residential and commercial projects from concept to completion.', reqs: ['Bachelor\'s in Architecture', '1-3 years of experience', 'Proficiency in AutoCAD & Revit', 'Strong design portfolio', 'Excellent communication skills'] },
  { id: 2, title: '3D Visualizer', type: 'Full-time', location: 'Remote', dept: 'Visualization', desc: 'Create stunning photorealistic renders and animations for our architectural projects.', reqs: ['Expert in 3ds Max, V-Ray or Lumion', '2+ years visualization experience', 'Understanding of architectural design', 'Strong artistic eye', 'Portfolio of architectural renders'] },
  { id: 3, title: 'Architecture Intern', type: 'Internship', location: 'Addis Ababa', dept: 'Design', desc: 'A 6-month internship program for architecture students to gain real-world project experience.', reqs: ['Currently enrolled in Architecture program', 'Basic CAD skills', 'Passion for design', 'Willingness to learn', 'Strong work ethic'] },
  { id: 4, title: 'Project Manager', type: 'Full-time', location: 'Addis Ababa', dept: 'Operations', desc: 'Lead project delivery, coordinate teams, and manage client relationships across multiple projects.', reqs: ['5+ years in project management', 'PMP certification preferred', 'Experience in construction/architecture', 'Strong leadership skills', 'Budget management experience'] },
];

export const blogs = [
  { id: 1, title: 'The Future of Sustainable Architecture in East Africa', category: 'Design Theory', excerpt: 'Exploring how climate-responsive design, local materials, and traditional building wisdom are shaping a new era of African architecture.', date: 'Mar 15, 2025', readTime: '8 min', bg: 1 },
  { id: 2, title: 'How Minimalism Shapes Modern Living Spaces', category: 'Project Breakdown', excerpt: 'A deep dive into the principles of minimalist design and how restraint can create spaces that feel both luxurious and liberating.', date: 'Feb 28, 2025', readTime: '6 min', bg: 2 },
  { id: 3, title: '5 Principles of Biophilic Design You Should Know', category: 'Construction Insights', excerpt: 'From natural light optimization to living walls, discover how reconnecting buildings with nature improves wellbeing and productivity.', date: 'Feb 10, 2025', readTime: '5 min', bg: 3 },
  { id: 4, title: 'Breaking Down the Design Process: From Brief to Build', category: 'Design Theory', excerpt: 'An insider look at how we approach projects — from initial client conversations through concept development to construction documentation.', date: 'Jan 22, 2025', readTime: '10 min', bg: 4 },
];

export const testimonials = [
  { id: 1, text: '"Nahom\'s design for our family home exceeded every expectation. The attention to detail and understanding of how we live was remarkable."', name: 'James Mitchell', company: 'Residential Client', rating: 5, initials: 'JM', gradient: 'linear-gradient(135deg, #3498db, #2980b9)' },
  { id: 2, text: '"Working with Nahom on our office redesign was seamless. He delivered on time, on budget, and the result transformed our workspace culture."', name: 'Aisha Rahman', company: 'Tech Startup CEO', rating: 5, initials: 'AR', gradient: 'linear-gradient(135deg, #e67e22, #d35400)' },
  { id: 3, text: '"The urban masterplan Nahom created for our district is visionary. It balances community needs with environmental responsibility perfectly."', name: 'Dr. Samuel Okoro', company: 'Urban Development Board', rating: 5, initials: 'SO', gradient: 'linear-gradient(135deg, #27ae60, #229954)' },
];
